document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.transform=`perspective(900px) rotateX(${(0.5-y)*4}deg) rotateY(${(x-0.5)*5}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')});

const heroSlides=[...document.querySelectorAll('.hero-slide')];const dotsWrap=document.querySelector('.slide-dots');let heroIndex=0,heroTimer;
function showHero(n){if(!heroSlides.length)return;heroIndex=(n+heroSlides.length)%heroSlides.length;heroSlides.forEach((s,i)=>s.classList.toggle('active',i===heroIndex));document.querySelectorAll('.slide-dot').forEach((d,i)=>d.classList.toggle('active',i===heroIndex))}
if(heroSlides.length&&dotsWrap){heroSlides.forEach((_,i)=>{const b=document.createElement('button');b.className='slide-dot'+(i===0?' active':'');b.setAttribute('aria-label',`Show slide ${i+1}`);b.addEventListener('click',()=>{showHero(i);restartHero()});dotsWrap.appendChild(b)});const startHero=()=>heroTimer=setInterval(()=>showHero(heroIndex+1),6800);const restartHero=()=>{clearInterval(heroTimer);startHero()};if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)startHero()}

const reveals=[...document.querySelectorAll('.reveal')];if(reveals.length){if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}})},{threshold:.12});reveals.forEach(el=>observer.observe(el))}else{reveals.forEach(el=>el.classList.add('in-view'))}}

const items=[...document.querySelectorAll('.gitem')];const lb=document.querySelector('.lightbox:not(.instrument-lightbox)');if(lb&&items.length){const im=lb.querySelector('.lb-img'),cap=lb.querySelector('.lb-caption');let i=0;const show=n=>{i=(n+items.length)%items.length;im.src=items[i].querySelector('img').src;cap.textContent=items[i].dataset.caption||items[i].querySelector('img').alt};const open=n=>{show(n);lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};const close=()=>{lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow=''};items.forEach((el,n)=>el.addEventListener('click',()=>open(n)));let touchStartX=0,touchStartY=0;lb.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;touchStartX=e.touches[0].clientX;touchStartY=e.touches[0].clientY},{passive:true});lb.addEventListener('touchend',e=>{if(e.changedTouches.length!==1)return;const dx=e.changedTouches[0].clientX-touchStartX,dy=e.changedTouches[0].clientY-touchStartY;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.2){if(dx<0)show(i+1);else show(i-1)}},{passive:true});lb.querySelector('.lb-prev').addEventListener('click',()=>show(i-1));lb.querySelector('.lb-next').addEventListener('click',()=>show(i+1));lb.querySelector('.lb-close').addEventListener('click',close);lb.addEventListener('click',e=>{if(!e.target.closest('.lb-img,.lb-btn,.lb-close,.lb-caption'))close()});document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')show(i-1);if(e.key==='ArrowRight')show(i+1)})}

const form=document.querySelector('#contact-form');if(form){form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent(`Website inquiry — ${data.get('service')||'General'}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nService: ${data.get('service')}\n\n${data.get('message')}`);window.location.href=`mailto:peterbonos@gmail.com?subject=${subject}&body=${body}`})}

const instrumentItems=[...document.querySelectorAll(".instrument-lightbox-item")];const instrumentLb=document.querySelector(".instrument-lightbox");if(instrumentLb&&instrumentItems.length){const im=instrumentLb.querySelector(".lb-img"),cap=instrumentLb.querySelector(".lb-caption");const close=()=>{instrumentLb.classList.remove("open");instrumentLb.setAttribute("aria-hidden","true");document.body.style.overflow=""};instrumentItems.forEach(el=>{el.setAttribute("tabindex","0");el.setAttribute("role","button");el.setAttribute("aria-label",`Expand ${el.querySelector("img").alt}`);const open=()=>{const src=el.querySelector("img");im.src=src.src;im.alt=src.alt;cap.textContent=el.querySelector(".instrument-cap strong")?.textContent||src.alt;instrumentLb.classList.add("open");instrumentLb.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"};el.addEventListener("click",open);el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})});instrumentLb.querySelector(".lb-close").addEventListener("click",close);instrumentLb.addEventListener("click",e=>{if(!e.target.closest(".lb-img,.lb-close,.lb-caption"))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&instrumentLb.classList.contains("open"))close()})}


const eventImages=[...document.querySelectorAll(".event-image")];const eventLb=document.querySelector(".event-lightbox");if(eventLb&&eventImages.length){const im=eventLb.querySelector(".event-lb-img");const close=()=>{eventLb.classList.remove("open");eventLb.setAttribute("aria-hidden","true");document.body.style.overflow=""};eventImages.forEach(el=>{el.setAttribute("tabindex","0");el.setAttribute("role","button");el.setAttribute("aria-label","Expand image: "+el.alt);const open=()=>{im.src=el.src;im.alt=el.alt;eventLb.classList.add("open");eventLb.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"};el.addEventListener("click",open);el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})});eventLb.querySelector(".event-lb-close").addEventListener("click",close);eventLb.addEventListener("click",e=>{if(e.target===eventLb)close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&eventLb.classList.contains("open"))close()})}
